// @ts-nocheck
// HandCaption V10 — browser-only/local media processing.
"use strict";

const U=[..."ABCDEFGHIJKLMNOPQRSTUVWXYZ"],L=[..."abcdefghijklmnopqrstuvwxyz"],D=[..."0123456789"],ALL=[...U,...L,...D];
const SEC=Object.freeze({MAX_PACKS:20,MAX_PACK_NAME:30,MAX_CAPTION:200,MAX_IMAGE_BYTES:15*1024*1024,MAX_VIDEO_BYTES:100*1024*1024,IMAGE_TYPES:["image/jpeg","image/png","image/webp"],VIDEO_TYPES:["video/mp4","video/webm","video/quicktime"]});
const $=id=>document.getElementById(id);
let selectedPackId=localStorage.getItem("handcaption_selected_pack")||"",currentEditingPackId=null,currentMediaType=null,baseImage=null,currentImageURL=null,currentVideoURL=null;
let captions=[],activeCaptionId=null,editorHistory=[],editorHistoryIndex=-1,dragging=false,dragOffset={x:0,y:0};
let glyphs=Object.create(null),currentCharIndex=0,writing=false,strokeHistory=[],strokeHistoryIndex=-1;
const wc=$('writingCanvas'),wctx=wc.getContext('2d',{willReadFrequently:true});
const glyphCache=new Map();

function safeArray(raw){try{const v=JSON.parse(raw||"[]");return Array.isArray(v)?v:[]}catch(_){return[]}}
function normalizePack(p,index){if(!p||typeof p!=="object"||!p.glyphs||typeof p.glyphs!=="object")return null;const id=String(p.id||`pack_${Date.now()}_${index}`).slice(0,100),name=String(p.name||"My Handwriting").replace(/[<>]/g,"").trim().slice(0,SEC.MAX_PACK_NAME)||"My Handwriting",g={};for(const c of ALL){if(typeof p.glyphs[c]==="string"&&p.glyphs[c].startsWith("data:image/png;base64,"))g[c]=p.glyphs[c]}return Object.keys(g).length===62?{id,name,characterCount:62,created:Number(p.created)||Date.now(),updated:Number(p.updated)||Date.now(),glyphs:g}:null}
function packs(){for(const key of ["handcaption_packs_v10","handcaption_packs_v9","handcaption_packs_v8","handcaption_packs_v7","handcaption_packs_v6","handcaption_packs_v5","handcaption_packs"]){const raw=localStorage.getItem(key);if(!raw)continue;const list=safeArray(raw).map(normalizePack).filter(Boolean).slice(0,SEC.MAX_PACKS);if(list.length){try{localStorage.setItem("handcaption_packs_v10",JSON.stringify(list))}catch(_){}return list}}return[]}
function savePacks(list){try{localStorage.setItem("handcaption_packs_v10",JSON.stringify(list.map(normalizePack).filter(Boolean).slice(0,SEC.MAX_PACKS)));return true}catch(_){alert("Storage is full. Delete an old handwriting pack or export a backup first.");return false}}
function selectedPack(){return packs().find(p=>p.id===selectedPackId)||null}
function blankCanvas(){const d=wctx.getImageData(0,0,wc.width,wc.height).data;for(let i=3;i<d.length;i+=4)if(d[i])return false;return true}
function snapshotStroke(){return blankCanvas()?"":wc.toDataURL("image/png")}
function updateStrokeButtons(){
  $('undoStroke').disabled=strokeHistoryIndex<=0;
  $('redoStroke').disabled=strokeHistoryIndex<0||strokeHistoryIndex>=strokeHistory.length-1;
}
function initStrokeHistory(src=""){
  strokeHistory=[src||""];strokeHistoryIndex=0;updateStrokeButtons();
}
function recordStrokeState(){const s=snapshotStroke();if(strokeHistory[strokeHistoryIndex]===s)return;strokeHistory=strokeHistory.slice(0,strokeHistoryIndex+1);strokeHistory.push(s);strokeHistoryIndex=strokeHistory.length-1;if(strokeHistory.length>30){strokeHistory.shift();strokeHistoryIndex--}updateStrokeButtons()}
function restoreStroke(i){if(i<0||i>=strokeHistory.length)return;wctx.clearRect(0,0,wc.width,wc.height);const src=strokeHistory[i];if(src){const im=new Image();im.onload=()=>{wctx.drawImage(im,0,0,wc.width,wc.height);updateWritingUI()};im.src=src}else updateWritingUI();strokeHistoryIndex=i;updateStrokeButtons()}
function captureGlyph(){glyphs[ALL[currentCharIndex]]=blankCanvas()?null:snapshotStroke()}
function setGlyphCanvas(src){wctx.clearRect(0,0,wc.width,wc.height);if(!src){initStrokeHistory("");updateWritingUI();return}const im=new Image();im.onload=()=>{wctx.drawImage(im,0,0,wc.width,wc.height);initStrokeHistory(src);updateWritingUI()};im.src=src}
function updateWritingUI(){const ch=ALL[currentCharIndex],done=ALL.filter(c=>!!glyphs[c]).length,written=!!glyphs[ch];$('currentChar').textContent=ch;$('guideChar').textContent=ch;$('charProgress').textContent=`${currentCharIndex+1} / 62`;$('charStatus').textContent=written?"✓ Written":blankCanvas()?"Not written":"Continue writing or tap Next →";$('charStatus').style.color=written?"#14733e":"#777";$('writingProgressBar').style.width=`${done/62*100}%`;$('backChar').disabled=currentCharIndex===0;$('nextChar').disabled=!written;$('nextChar').textContent=currentCharIndex===61?"Finish ✓":"Next →";$('progressText').textContent=`${done} / 62 completed`;$('progressMessage').textContent=done===62?"✓ All characters completed. You can save this pack.":`${62-done} character${62-done===1?"":"s"} remaining.`;$('progressBar').style.width=`${done/62*100}%`;$('savePack').disabled=done!==62;const list=$('characterChecklist');list.replaceChildren();ALL.forEach((c,i)=>{const b=document.createElement('button');b.type='button';b.className='character-check'+(glyphs[c]?' done':'')+(i===currentCharIndex?' current':'');b.textContent=c;b.onclick=()=>goToCharacter(i);list.append(b)});updateStrokeButtons()}
function goToCharacter(i){if(i<0||i>=62)return;captureGlyph();currentCharIndex=i;setGlyphCanvas(glyphs[ALL[i]]||"");}
function clearCurrentCharacter(){wctx.clearRect(0,0,wc.width,wc.height);glyphs[ALL[currentCharIndex]]=null;initStrokeHistory("");updateWritingUI()}
function resetNewPack(name="My Handwriting"){glyphs=Object.create(null);currentCharIndex=0;currentEditingPackId=null;$('packName').value=name;wctx.clearRect(0,0,wc.width,wc.height);initStrokeHistory("");updateWritingUI();lockMedia()}
function startWriting(e){e.preventDefault();writing=true;try{wc.setPointerCapture(e.pointerId)}catch(_){}const r=wc.getBoundingClientRect();wctx.beginPath();wctx.moveTo((e.clientX-r.left)*wc.width/r.width,(e.clientY-r.top)*wc.height/r.height)}
function moveWriting(e){if(!writing)return;e.preventDefault();const r=wc.getBoundingClientRect(),x=(e.clientX-r.left)*wc.width/r.width,y=(e.clientY-r.top)*wc.height/r.height;wctx.lineCap='round';wctx.lineJoin='round';wctx.lineWidth=8;wctx.strokeStyle='#111';wctx.lineTo(x,y);wctx.stroke();$('charStatus').textContent='Writing…'}
function stopWriting(e){if(!writing)return;writing=false;try{if(e)wc.releasePointerCapture(e.pointerId)}catch(_){}recordStrokeState();$('charStatus').textContent=blankCanvas()?"Not written":"Continue writing or tap Next →"}
wc.style.touchAction='none';wc.addEventListener('pointerdown',startWriting);wc.addEventListener('pointermove',moveWriting);wc.addEventListener('pointerup',stopWriting);wc.addEventListener('pointercancel',stopWriting);wc.addEventListener('pointerleave',e=>{if(writing)stopWriting(e)});
$('undoStroke').onclick=()=>restoreStroke(strokeHistoryIndex-1);$('redoStroke').onclick=()=>restoreStroke(strokeHistoryIndex+1);$('redrawChar').onclick=clearCurrentCharacter;
$('backChar').onclick=()=>{captureGlyph();goToCharacter(currentCharIndex-1)};
$('nextChar').onclick=()=>{captureGlyph();if(!glyphs[ALL[currentCharIndex]])return alert('Write the complete character before continuing.');if(currentCharIndex<61)goToCharacter(currentCharIndex+1);else updateWritingUI()};
$('clearPack').onclick=()=>{if(confirm('Erase all 62 characters?'))resetNewPack()};$('newPack').onclick=()=>{resetNewPack('New Handwriting');scrollTo({top:0,behavior:'smooth'})};
$('savePack').onclick=()=>{captureGlyph();if(ALL.some(c=>!glyphs[c]))return alert('Complete all 62 characters first.');const ps=packs(),name=$('packName').value.replace(/[<>]/g,'').trim().slice(0,SEC.MAX_PACK_NAME)||'My Handwriting';let p=currentEditingPackId?ps.find(x=>x.id===currentEditingPackId):null;if(!p){if(ps.length>=SEC.MAX_PACKS)return alert('You can keep up to 20 handwriting packs.');p={id:`pack_${Date.now()}_${Math.random().toString(36).slice(2)}`,created:Date.now()};ps.push(p)}p.name=name;p.updated=Date.now();p.characterCount=62;p.glyphs={};for(const c of ALL)p.glyphs[c]=glyphs[c];if(savePacks(ps)){currentEditingPackId=p.id;selectedPackId=p.id;localStorage.setItem('handcaption_selected_pack',p.id);renderPacks();unlockMedia();alert('✓ Handwriting pack saved.')}};
function loadPack(id){const p=packs().find(x=>x.id===id);if(!p)return;currentEditingPackId=id;$('packName').value=p.name;glyphs=Object.assign(Object.create(null),p.glyphs);currentCharIndex=0;setGlyphCanvas(glyphs.A||"");scrollTo({top:0,behavior:'smooth'})}
function deletePack(id){const p=packs().find(x=>x.id===id);if(!p||!confirm(`Delete "${p.name}"?`))return;const next=packs().filter(x=>x.id!==id);savePacks(next);if(selectedPackId===id)selectedPackId=next[0]?.id||'';if(currentEditingPackId===id)currentEditingPackId=null;localStorage.setItem('handcaption_selected_pack',selectedPackId);renderPacks()}
$('deletePack').onclick=()=>selectedPackId&&deletePack(selectedPackId);
function selectPack(id){if(!packs().some(p=>p.id===id))return;selectedPackId=id;localStorage.setItem('handcaption_selected_pack',id);renderPacks();renderCurrentMedia()}
$('packSelect').onchange=()=>selectPack($('packSelect').value);
function renderPacks(){const ps=packs();$('savedPacks').replaceChildren();$('packSelect').replaceChildren();if(!ps.length){const o=document.createElement('option');o.textContent='No pack selected';o.value='';$('packSelect').append(o);$('deletePack').disabled=true;lockMedia();return}if(!selectedPackId||!ps.some(p=>p.id===selectedPackId))selectedPackId=ps[0].id;localStorage.setItem('handcaption_selected_pack',selectedPackId);ps.forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;$('packSelect').append(o);const item=document.createElement('div');item.className='pack-item'+(p.id===selectedPackId?' selected':'');const n=document.createElement('strong');n.textContent='✍️ '+p.name;const s=document.createElement('small');s.textContent='62 characters';const bs=document.createElement('div');bs.className='pack-buttons';[['Use','primary',()=>selectPack(p.id)],['Edit','ghost',()=>loadPack(p.id)],['Delete','danger',()=>deletePack(p.id)]].forEach(([txt,cl,fn])=>{const b=document.createElement('button');b.className=cl;b.textContent=txt;b.onclick=fn;bs.append(b)});item.append(n,s,bs);$('savedPacks').append(item)});$('packSelect').value=selectedPackId;$('deletePack').disabled=false;unlockMedia()}
function lockMedia(){$('mediaSection').classList.add('locked');$('lockedMessage').classList.remove('hidden');$('packSelect').disabled=true;$('chooseMediaButton').disabled=true}
function unlockMedia(){$('mediaSection').classList.remove('locked');$('lockedMessage').classList.add('hidden');$('packSelect').disabled=false;$('chooseMediaButton').disabled=!selectedPackId}

$('exportPack').onclick=()=>{const p=selectedPack()||((ALL.every(c=>!!glyphs[c]))?{id:'draft',name:$('packName').value||'My Handwriting',characterCount:62,created:Date.now(),updated:Date.now(),glyphs}:null);if(!p)return alert('Select or complete a handwriting pack first.');const blob=new Blob([JSON.stringify({format:'HandCaption V10 pack',version:10,pack:p},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${p.name.replace(/[^a-z0-9_-]+/gi,'_')||'handwriting'}-handcaption.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('importPack').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const data=JSON.parse(await f.text()),p=normalizePack(data.pack||data,0);if(!p)throw Error();const ps=packs();const existing=ps.find(x=>x.name.toLowerCase()===p.name.toLowerCase());if(existing){if(!confirm(`A pack named "${p.name}" already exists. Replace it?`)){e.target.value='';return}p.id=existing.id;const next=ps.map(x=>x.id===existing.id?p:x);savePacks(next)}else{if(ps.length>=SEC.MAX_PACKS)throw Error('limit');savePacks([...ps,p])}selectedPackId=p.id;localStorage.setItem('handcaption_selected_pack',p.id);renderPacks();alert('✓ Pack imported.')}catch(err){alert(err.message==='limit'?'Maximum 20 packs reached.':'Invalid HandCaption pack file.')}e.target.value=''};

function validFile(f){if(!f)return{ok:false,msg:'No file selected.'};if(SEC.IMAGE_TYPES.includes(f.type)&&f.size<=SEC.MAX_IMAGE_BYTES)return{ok:true,type:'image'};if(SEC.VIDEO_TYPES.includes(f.type)&&f.size<=SEC.MAX_VIDEO_BYTES)return{ok:true,type:'video'};return{ok:false,msg:'Unsupported or oversized file. Images: JPEG/PNG/WebP up to 15 MB. Videos: MP4/WebM/MOV up to 100 MB.'}}
function releaseURLs(){if(currentImageURL){URL.revokeObjectURL(currentImageURL);currentImageURL=null}if(currentVideoURL){URL.revokeObjectURL(currentVideoURL);currentVideoURL=null}}
function clearEditor(){captions=[];activeCaptionId=null;editorHistory=[];editorHistoryIndex=-1;$('captionLayers').replaceChildren();$('captionInput').value='';updateHistoryButtons()}
function addMedia(){$('mediaInput').click()};$('chooseMediaButton').onclick=addMedia;$('addMediaButton').onclick=addMedia;
$('mediaInput').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const v=validFile(f);if(!v.ok){alert(v.msg);e.target.value='';return}releaseURLs();clearEditor();$('editorWrap').classList.remove('hidden');if(v.type==='image'){currentMediaType='image';$('mediaType').textContent='PHOTO';$('imageEditor').classList.remove('hidden');$('videoEditor').classList.add('hidden');currentImageURL=URL.createObjectURL(f);const im=new Image();im.onload=()=>{baseImage=im;fitImage()};im.onerror=()=>{releaseURLs();alert('Could not open this image.')};im.src=currentImageURL}else{currentMediaType='video';$('mediaType').textContent='VIDEO';$('imageEditor').classList.add('hidden');$('videoEditor').classList.remove('hidden');currentVideoURL=URL.createObjectURL(f);const video=$('videoPreview');video.src=currentVideoURL;video.load();video.onloadedmetadata=()=>{$('videoOverlay').width=video.videoWidth||1280;$('videoOverlay').height=video.videoHeight||720;for(const c of captions)c.end=video.duration;drawVideo()}}e.target.value=''};
$('removeMedia').onclick=()=>{releaseURLs();baseImage=null;currentMediaType=null;clearEditor();$('videoPreview').pause();$('videoPreview').removeAttribute('src');$('videoPreview').load();$('editorWrap').classList.add('hidden')};
function fitImage(){if(!baseImage)return;const s=Math.min(1200/baseImage.width,800/baseImage.height,1);$('editorCanvas').width=Math.round(baseImage.width*s);$('editorCanvas').height=Math.round(baseImage.height*s);drawImage()}

function activeCaption(){return captions.find(c=>c.id===activeCaptionId)||null}
function createCaption(){if(captions.length>=15){alert('Maximum 15 caption layers.');return null}const end=currentMediaType==='video'&&$('videoPreview').duration?$('videoPreview').duration:0;return{id:`cap_${Date.now()}_${Math.random().toString(36).slice(2)}`,text:$('captionInput').value.trim().slice(0,SEC.MAX_CAPTION),x:($('editorCanvas').width||$('videoOverlay').width)*.08,y:($('editorCanvas').height||$('videoOverlay').height)*.82,size:+$('sizeInput').value,color:$('colorInput').value,rotation:+$('rotationInput').value,spacing:+$('spacingInput').value,shadow:+$('shadowInput').value,opacity:+$('opacityInput').value,animation:$('animationInput').value,duration:+$('durationInput').value,start:0,end}}
function readControls(c){c.text=$('captionInput').value.slice(0,SEC.MAX_CAPTION);c.size=+$('sizeInput').value;c.color=$('colorInput').value;c.rotation=+$('rotationInput').value;c.spacing=+$('spacingInput').value;c.shadow=+$('shadowInput').value;c.opacity=+$('opacityInput').value;c.animation=$('animationInput').value;c.duration=+$('durationInput').value;c.start=Math.max(0,+$('startInput').value||0);c.end=Math.max(0,+$('endInput').value||0);if(currentMediaType==='video'&&$('videoPreview').duration&&c.end>0)c.end=Math.min(c.end,$('videoPreview').duration);return c}
function syncControls(){const c=activeCaption();if(!c)return;$('captionInput').value=c.text;$('sizeInput').value=c.size;$('colorInput').value=c.color;$('rotationInput').value=c.rotation;$('spacingInput').value=c.spacing??4;$('shadowInput').value=c.shadow??8;$('opacityInput').value=c.opacity??1;$('animationInput').value=c.animation||'none';$('durationInput').value=c.duration||1.2;$('startInput').value=c.start||0;$('endInput').value=c.end||0}
function saveEditorHistory(){const s=JSON.stringify({captions,activeCaptionId});if(editorHistory[editorHistoryIndex]===s)return;editorHistory=editorHistory.slice(0,editorHistoryIndex+1);editorHistory.push(s);editorHistoryIndex=editorHistory.length-1;if(editorHistory.length>40){editorHistory.shift();editorHistoryIndex--}updateHistoryButtons()}
function updateHistoryButtons(){$('undoEdit').disabled=editorHistoryIndex<=0;$('redoEdit').disabled=editorHistoryIndex<0||editorHistoryIndex>=editorHistory.length-1}
function restoreEditorHistory(i){if(i<0||i>=editorHistory.length)return;const s=JSON.parse(editorHistory[i]);captions=s.captions||[];activeCaptionId=s.activeCaptionId||null;editorHistoryIndex=i;renderLayerUI();syncControls();renderCurrentMedia();updateHistoryButtons()}
$('undoEdit').onclick=()=>restoreEditorHistory(editorHistoryIndex-1);$('redoEdit').onclick=()=>restoreEditorHistory(editorHistoryIndex+1);
function renderLayerUI(){const box=$('captionLayers');box.replaceChildren();captions.forEach((c,i)=>{const b=document.createElement('button');b.type='button';b.className='layer-pill'+(c.id===activeCaptionId?' active':'');b.textContent=`${i+1}. ${c.text.slice(0,18)||'Caption'}`;b.onclick=()=>{activeCaptionId=c.id;syncControls();renderLayerUI();renderCurrentMedia()};box.append(b)})}
$('addCaption').onclick=()=>{if(!selectedPack())return alert('Select a handwriting pack.');const text=$('captionInput').value.trim();if(!text)return alert('Type a caption.');let c=activeCaption();if(c)readControls(c);else{c=createCaption();if(!c)return;readControls(c);captions.push(c);activeCaptionId=c.id}saveEditorHistory();renderLayerUI();renderCurrentMedia()};
$('duplicateCaption').onclick=()=>{const c=activeCaption();if(!c)return;const n=JSON.parse(JSON.stringify(c));n.id=`cap_${Date.now()}_${Math.random().toString(36).slice(2)}`;n.x+=25;n.y+=25;captions.push(n);activeCaptionId=n.id;saveEditorHistory();renderLayerUI();syncControls();renderCurrentMedia()};
$('deleteCaption').onclick=()=>{if(!activeCaptionId)return;captions=captions.filter(c=>c.id!==activeCaptionId);activeCaptionId=captions[0]?.id||null;saveEditorHistory();renderLayerUI();if(activeCaptionId)syncControls();renderCurrentMedia()};
['captionInput','sizeInput','colorInput','rotationInput','spacingInput','shadowInput','opacityInput','animationInput','durationInput','startInput','endInput'].forEach(id=>$(id).addEventListener('change',()=>{const c=activeCaption();if(!c)return;readControls(c);saveEditorHistory();renderLayerUI();renderCurrentMedia()}));

function animationProgress(c,time){const d=Math.max(.2,+c.duration||1.2),local=Math.max(0,time-(+c.start||0));if(c.animation==='none')return 1;return Math.max(0,Math.min(1,local/d))}
function visibleCaption(c,time){if(currentMediaType!=='video')return true;const start=+c.start||0,end=+c.end||0;return time>=start&&(end<=0||time<=end)}
function loadGlyph(src){if(glyphCache.has(src))return Promise.resolve(glyphCache.get(src));return new Promise((res,rej)=>{const im=new Image();im.onload=()=>{glyphCache.set(src,im);res(im)};im.onerror=rej;im.src=src})}
function hexRGB(hex){const n=parseInt(hex.replace('#',''),16);return[(n>>16)&255,(n>>8)&255,n&255]}
async function drawCaption(ctx,c,time=0,scale=1){const p=selectedPack();if(!p||!visibleCaption(c,time)||!c.text)return;const progress=animationProgress(c,time);let alpha=(c.opacity??1),off=0,sc=1;if(c.animation==='fade')alpha*=progress;if(c.animation==='slide'){alpha*=progress;off=(1-progress)*80*scale}if(c.animation==='pop'){alpha*=progress;sc=.75+.25*progress}const chars=c.animation==='write'?Math.ceil(c.text.length*progress):c.text.length;ctx.save();ctx.globalAlpha=alpha;ctx.translate(c.x+off,c.y);ctx.rotate((c.rotation*Math.PI)/180);ctx.scale(sc,sc);let x=0;const k=(c.size*scale)/90;for(let i=0;i<chars;i++){const ch=c.text[i],src=p.glyphs?.[ch];if(src){try{const im=await loadGlyph(src),w=180*k,h=90*k;if(c.shadow>0){ctx.save();ctx.shadowColor='rgba(0,0,0,.55)';ctx.shadowBlur=c.shadow*scale;ctx.shadowOffsetX=c.shadow*.45*scale;ctx.shadowOffsetY=c.shadow*.45*scale;drawTintedGlyph(ctx,im,x,-h*.75,w,h,c.color);ctx.restore()}else drawTintedGlyph(ctx,im,x,-h*.75,w,h,c.color);x+=w*.55+(c.spacing*scale)}catch(_){} }else{ctx.fillStyle=c.color;ctx.font=`${c.size*scale}px cursive`;ctx.textBaseline='alphabetic';ctx.shadowColor=c.shadow?'rgba(0,0,0,.55)':'transparent';ctx.shadowBlur=c.shadow*scale;ctx.fillText(ch,x,0);x+=ctx.measureText(ch).width+c.spacing*scale}}ctx.restore()}
function drawTintedGlyph(ctx,im,x,y,w,h,color){const [r,g,b]=hexRGB(color),off=document.createElement('canvas');off.width=Math.max(1,Math.ceil(w));off.height=Math.max(1,Math.ceil(h));const o=off.getContext('2d');o.drawImage(im,0,0,off.width,off.height);o.globalCompositeOperation='source-in';o.fillStyle=`rgb(${r},${g},${b})`;o.fillRect(0,0,off.width,off.height);ctx.drawImage(off,x,y,w,h)}
async function drawImage(time=0){if(!baseImage)return;const c=$('editorCanvas'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(baseImage,0,0,c.width,c.height);for(const cap of captions)await drawCaption(ctx,cap,time,1)}
async function drawVideo(){const c=$('videoOverlay'),video=$('videoPreview');if(!c.width||!selectedPackId)return;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);for(const cap of captions)await drawCaption(ctx,cap,video.currentTime,c.width/1000)}
function renderCurrentMedia(){if(currentMediaType==='image')drawImage(0);if(currentMediaType==='video')drawVideo()}
$('videoPreview').addEventListener('timeupdate',drawVideo);$('videoPreview').addEventListener('play',()=>{const loop=()=>{if($('videoPreview').paused)return;drawVideo();requestAnimationFrame(loop)};requestAnimationFrame(loop)});

function canvasPoint(c,e){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}
$('editorCanvas').addEventListener('pointerdown',e=>{const c=activeCaption();if(!c)return;const p=canvasPoint($('editorCanvas'),e);if(Math.abs(p.x-c.x)<260&&Math.abs(p.y-c.y)<Math.max(120,c.size*1.5)){dragging=true;dragOffset={x:p.x-c.x,y:p.y-c.y};try{$('editorCanvas').setPointerCapture(e.pointerId)}catch(_){}}});
$('editorCanvas').addEventListener('pointermove',e=>{if(!dragging)return;const c=activeCaption();if(!c)return;const p=canvasPoint($('editorCanvas'),e);c.x=Math.max(0,Math.min($('editorCanvas').width,p.x-dragOffset.x));c.y=Math.max(0,Math.min($('editorCanvas').height,p.y-dragOffset.y));drawImage()});
$('editorCanvas').addEventListener('pointerup',e=>{if(dragging){dragging=false;try{$('editorCanvas').releasePointerCapture(e.pointerId)}catch(_){}saveEditorHistory();renderLayerUI()}});$('editorCanvas').addEventListener('pointercancel',()=>dragging=false);

$('exportBtn').onclick=async()=>{if(currentMediaType==='image')return exportImage();if(currentMediaType==='video')return exportVideo()};
async function exportImage(){await drawImage(0);const c=$('editorCanvas'),blob=await new Promise(r=>c.toBlob(r,'image/png',1));if(!blob)return alert('Image export failed.');downloadBlob(blob,'handcaption.png')}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.rel='noopener';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function exportVideo(){const video=$('videoPreview'),comp=$('videoComposite');if(!video.src)return alert('Choose a video first.');if(!window.MediaRecorder||!comp.captureStream)return alert('This browser does not support local video export. Photo export still works.');const w=video.videoWidth||1280,h=video.videoHeight||720;comp.width=w;comp.height=h;const ctx=comp.getContext('2d');const source=video.captureStream();const stream=comp.captureStream(30);for(const t of source.getAudioTracks())stream.addTrack(t);const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime)return alert('No supported WebM export format was found.');const chunks=[],rec=new MediaRecorder(stream,{mimeType:mime});rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};rec.onerror=()=>alert('Video export failed.');const old=video.currentTime;video.currentTime=0;let raf=0;const frame=async()=>{if(video.paused&&video.currentTime<video.duration)return;ctx.clearRect(0,0,w,h);ctx.drawImage(video,0,0,w,h);for(const cap of captions)await drawCaption(ctx,cap,video.currentTime,w/1000);if(!video.ended)raf=requestAnimationFrame(frame)};rec.onstop=()=>{cancelAnimationFrame(raf);video.pause();video.currentTime=old;downloadBlob(new Blob(chunks,{type:mime}),'handcaption-video.webm')};rec.start(250);await video.play().catch(()=>{});frame();video.onended=()=>{if(rec.state!=='inactive')rec.stop()}}

function startup(){const ps=packs();if(ps.length){if(!selectedPackId||!ps.some(p=>p.id===selectedPackId))selectedPackId=ps[0].id;localStorage.setItem('handcaption_selected_pack',selectedPackId);renderPacks()}else lockMedia();initStrokeHistory('');updateWritingUI()}
window.addEventListener('pagehide',releaseURLs);startup();
